### ISSUE TITLE
Rename this repo to remove "sample"

### ISSUE THREAD

**Issue by Cadair** [sunpy/sample-data#24]
### Provide a general description of the issue or problem.

It's rapidly becoming the one true data repo for all.

**Comment by Cadair** [comment]
This also has the same issue as #25 which is that it relies on GH permo redirecting to not break old URLs which we have hardcoded into many a release of sunpy.

**Comment by nabobalis** [comment]
Shall we leave this alone then?

**Comment by ConorMacBride** [comment]
Similar to what I posted in #25, any sunpy versions which are relying on the current GitHub URL should be able to fall back to `http://data.sunpy.org/sunpy/v1/`.

**Comment by ConorMacBride** [comment]
Given the discussion in #25, it should be fine to rename the repo `data` now as this would be backwards compatible? If @Cadair wants to keep a low AWS bill we could update `_sample.py` to
```
_BASE_URLS = (
    'https://github.com/sunpy/sample-data/raw/master/sunpy/v1/',
    'https://github.com/sunpy/data/raw/master/sunpy/v1/',
    'http://data.sunpy.org/sunpy/v1/',
)
```
and then, for `v5.0.0`, rename the repo to `data` and remove the URL for `sunpy/sample-data`.

**Comment by Cadair** [comment]
we are now having the same discussion in two places so I am going to close this and make #25 the single issue for all the renaming.
