### ISSUE TITLE
Rename master branch to main and rename repo to `data`

### ISSUE THREAD

**Issue by dstansby** [sunpy/sample-data#25]

**Comment by Cadair** [comment]
I think this choice needs some serious consideration on this repo. We have raw.github.com urls with `master` in them hardcoded back for probably pushing 10 years at this point. Relying on Github to redirect forever seems not-great.

**Comment by dstansby** [comment]
Good point - I just knee jerk opened this PR without really thinking about it further 😆

**Comment by nabobalis** [comment]
Shall we leave this alone then due to that?

**Comment by dstansby** [comment]
How about leaving `master`, branching off it to create `main`, and setting `main` as the deafult, and changing to using `main` in sunpy 4.1?

**Comment by ConorMacBride** [comment]
Looking back through the git history:

- Remote sample data started [in `v0.6.0` (31st July 2015)](https://github.com/sunpy/sunpy/blob/62fa22b84bb6abe1611d0371554306170eec35b0/sunpy/data/_sample.py#L24-L26) and was accessible from:
  ```
  http://data.sunpy.org/sample-data/
  http://hesperia.gsfc.nasa.gov/~schriste/sunpy-sample-data/
  https://github.com/ehsteve/sunpy-sample-data/raw/master/
  ```
  None of these URLs are accessible today.

- [In version `v0.8.0` (17th August 2017)](https://github.com/sunpy/sunpy/blob/ce37e2a03cd9d3986c40ad265d85b3aea7e710c2/sunpy/data/_sample.py#L23-L24) these URLs were changed to the URLs we have today:
  ```
  http://data.sunpy.org/sunpy/v1/
  https://github.com/sunpy/sample-data/raw/master/sunpy/v1/
  ```

So renaming `master` to `main` is a backwards compatible change as any SunPy versions which are currently working (i.e., `sunpy>=0.8.0`) will be able to access the data via `http://data.sunpy.org/sunpy/v1/`.

I like `data.sunpy.org` as it's a domain that SunPy controls. This allows for better backwards compatibility as we're not relying that GitHub will always exist, continue to allow hosting, and not change their URL patterns. Is that the intension of `data.sunpy.org`? Are we using the GitHub URL as we have unlimited LFS bandwidth and AWS would charge more if everyone was using `data.sunpy.org`?

Should we fix versions `v0.6.0` to `v0.8.0` by making the `http://data.sunpy.org/sample-data/` URL work again? Also, HTTPS doesn't seem to be set up on `data.sunpy.org`.

**Comment by Cadair** [comment]
> None of these URLs are accessible today.

huh, I really thought that we kept `/sample-data` working, maybe we gave up on that a while ago.

> Should we fix versions v0.6.0 to v0.8.0 by making the http://data.sunpy.org/sample-data/ URL work again?

Seems a little redundant at this point, unless we only recently broke it.

> So renaming master to main is a backwards compatible change as any SunPy versions which are currently working (i.e., sunpy>=0.8.0) will be able to access the data via http://data.sunpy.org/sunpy/v1/.

This is an excellent point, and is probably all we needed to realise to be able to happily make this change.

> Is that the intension of data.sunpy.org?

One of the purposes yes. Mirrors for this stuff means it's just significantly more likely to work more of the time.

> Are we using the GitHub URL as we have unlimited LFS bandwidth and AWS would charge more if everyone was using data.sunpy.org?

Yes, since we changed the default URL from S3 to GH my monthly AWS bill has dropped from about £5 to pennies.

> Also, HTTPS doesn't seem to be set up on data.sunpy.org.

You can't do HTTPS directly out of an S3 bucket so we would need to add a CDN or similar which is more money for little gain imo?

**Comment by ConorMacBride** [comment]
You're right, the old URLs such as http://data.sunpy.org/sample-data/AIA20110319_105400_0171.fits are still working fine so downloads still work for `sunpy<0.8.0`! I must have tested the base URL on a newer file which was not available then.

So I guess we can rename the branch? This is assuming we only care about URLs for the sample data located in `sunpy.data._sample`, as I haven't checked if there are direct links to specific files elsewhere, such as in old sunpy examples or other repositories.

**Comment by Cadair** [comment]
I think we can rename it, we need to check that other projects like IRIS aren't relying on a single GH url.

We should however be ready to patch sunpy 4.0 quickly (or even patch it before we rename) to reduce the amount of hits we get which fallback to the data.sunpy.org mirror, and we should obviously do both the renames at once.

**Comment by Cadair** [comment]
Copying a little from @ConorMacBride's comment in #24 I think the best plan is the following:

* Patch sunpy 4.0 and main to use three URLs, the two current ones and the expected new one. So we end up with this
```
_BASE_URLS = (
    'https://github.com/sunpy/data/raw/main/sunpy/v1/',
    'https://github.com/sunpy/sample-data/raw/master/sunpy/v1/',
    'http://data.sunpy.org/sunpy/v1/',
)
```
* Then rename the repo to `data` and rename the branch to `main` once that change has been released.

**Comment by Cadair** [comment]
@DanRyanIrish @wtbarnes @nabobalis Packages you maintain have data in this repo, will this plan cause you issues?

**Comment by nabobalis** [comment]
I can change my code. This goes for aiapy and irispy

**Comment by nabobalis** [comment]
sunpy PR https://github.com/sunpy/sunpy/pull/6289

**Comment by Cadair** [comment]
We now need to await the next bugfix release of sunpy before we do anything else.

**Comment by nabobalis** [comment]
sunpy bugfix release is out.

**Comment by Cadair** [comment]
it is done. GH is not double redirecting so the old URLs do not work.
