### ISSUE TITLE
Add nice script to resample and rice compress files

### ISSUE THREAD

**Issue by nabobalis** [sunpy/sample-data#35]
### Describe the feature

Would make life easier for anyone who wants to add a new file.

**Comment by wtbarnes** [comment]
For the sample data?

**Comment by nabobalis** [comment]
Yes. I want it add a 304 and I have no idea what size the others are without opening it. 

A script someone can use to add sample data would be nice.

**Comment by nabobalis** [comment]
Turns out not hard to do if you use Map for a 2D image.

**Comment by nabobalis** [comment]
Oh one even exists I was just blind.
